Animal shelter saman
mapbox/maki pull request #558
Opened 2021-09-24 17:41 UTC by samanpwbb

2021-09-24 21:19 UTC, samanpwbb commented on browser.esm.js
> +export const svgArray = ["\u0000\u0000\u0000\u0001Bud1\u0000\u0000\u0010\u0000\u0000\u0000\b\u0000\u0000\u0000\u0010\u0000\u0000\u0000\u0000%\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u00
this looks wrong 🤔

2021-09-27 19:46 UTC, tristen requested changes
The silhouette and legibility look great. I just have some minor comments on some of the anchor points 

| Round `x` `y` coordinates | Superflous points | 
| --- | --- |
| <img width="1053" alt="Screen Shot 2021-09-27 at 3 39 40 PM" src="https://user-images.githubusercontent.com/61150/134974827-7688a95b-e0ab-47f6-8f43-955d74608db7.png"> | <img width="632" alt="Screen Shot 2021-09-27 at 3 39 49 PM" src="https://user-images.githubusercontent.com/61150/134974830-0a59e1e7-3af4-4287-b7f0-74b38364011f.png"> |

2021-09-27 19:46 UTC, tristen commented on scripts/gather-files.js
> +  const list = fs.readdirSync(dir).filter(item => !hiddenFileRegex.test(item));
Oh nice catch. Couldn't this be much simpler and exclude anything that isn't .svg  i.e `.filter(item => item.match(/.svg$/))`?

2021-09-28 03:44 UTC, samanpwbb commented
Lol no, wait, I don't have permission to commit any more. One sec.

2021-09-28 14:15 UTC, tristen commented
👉 https://github.com/mapbox/maki/pull/559

2021-09-28 14:18 UTC, tristen approved these changes
😭

2021-09-28 14:19 UTC, merged