Add build command for maki icons with metadata for styling
mapbox/maki pull request #594
Opened 2024-12-23 21:39 UTC by tristen

2025-01-02 20:07 UTC, AlexanderBelokon requested changes
The output looks good (I think), but I would like to see a few changes, namely:

- a snapshot test that confirms there will be no regressions in metadata format
- `prettier` run on the output files
- async/await in scripts to ensure code is more maintainable and exceptions are handled correctly
- use of native node fs/async tools so that we don't have to maintain extra external deps anymore

2025-01-03 20:07 UTC, AlexanderBelokon approved these changes
Thank you, that looks much nicer 👍

I added a few additional suggestions, but won't block the release anymore

2025-01-03 20:07 UTC, AlexanderBelokon commented on .npmignore
> +icons-meta
Should we also exclude build tools and tests from the npm package?

```suggestion
icons-meta
.travis.yml
eslint.config.mjs
scripts
test
```

2025-01-03 20:07 UTC, AlexanderBelokon commented on scripts/utils.js
> +  const svgFiles = files.filter(f => f.indexOf('.svg') !== -1);
Maybe a little more modern here too?

```suggestion
  const svgFiles = files.filter(f => f.endsWith('.svg'));
```

2025-01-07 12:17 UTC, woodroof commented on scripts/make-meta-icons.js
> +    data.path.unshift({
Now stroke paths also have fill parts, so they will be rendered twice. It's not visible as our colors are not transparent, but not optimal.
P.S. Am I right that mapnik doesn't support `paint-order` attribute? If it does, it's better to just put `paint-order: stroke` and not duplicate the entire path.

2025-02-20 15:55 UTC, tristen commented on scripts/make-meta-icons.js
> +    data.path.unshift({
Ahhhh this would be good to confirm. I was sort of mirroring behavior we do today for the maki editor but it might be as simple as using stoke differently. Going to treat that as a followup and merge+publish this for now.

2025-02-20 15:55 UTC, merged